server:
  port: 18888
spring:
  security:
    user:
      name: muyi
      password: 12345
  thymeleaf:
    cache: false
    encoding: UTF-8
  datasource:
    url:
    driver-class-name:
    password:
    name:
logging:
  level:
    com.example.dss: debug
